server:
  port: 8080  # 서버 포트 설정

spring:
  thymeleaf:
    prefix: classpath:/templates/  # Thymeleaf 템플릿 파일 경로
    suffix: .html  # Thymeleaf 템플릿 파일 확장자
    mode: HTML  # Thymeleaf 렌더링 모드
    cache: false  # 개발 시에는 캐싱 비활성화 (프로덕션에서는 true로 설정 권장)

  mvc:
    static-path-pattern: /static/**  # 정적 리소스 경로 설정
    view:
      prefix: classpath:/templates/  # Thymeleaf 템플릿 파일 경로
      suffix: .html  # Thymeleaf 템플릿 파일 확장자

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver  # MySQL JDBC 드라이버
    url: jdbc:mysql://db-pf25p-kr.vpc-pub-cdb.ntruss.com:3306/studydb?serverTimezone=Asia/Seoul  # 데이터베이스 URL
    username: study  # 데이터베이스 사용자 이름
    password: bitcamp123!@#  # 데이터베이스 비밀번호
    hikari:
      maximum-pool-size: 20  # HikariCP 커넥션 풀 크기 설정

#  jpa:
#    hibernate:
#      ddl-auto: update  # 데이터베이스 스키마 업데이트 (운영 환경에서는 주의)
#    show-sql: true  # SQL 쿼리 콘솔 출력 활성화
#    properties:
#      hibernate:
#        format_sql: true  # SQL 쿼리 포맷팅

#  jackson:
#    serialization:
#      fail-on-empty-beans: false  # 빈 객체 직렬화 오류 방지

mybatis:
  configuration:
    # 스네이크 케이스와 카멜 케이스 매핑을 자동으로 처리
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mapper/**/*Mapper.xml  # MyBatis 매퍼 파일 경로 설정

ncp:
  accessKey: 45ACB51A1BAE3E46F3F8
  secretKey: 92678775703FF4ABA952C6FB668A4D4EBDCB42DD
  regionName: kr-standard
  endPoint: https://kr.object.ncloudstorage.com
  bucketName: bitcamp-9th-bucket-135